services:
  flora-core:
    build:
      context: ./flora-core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  flora-worker:
    build:
      context: ./flora-worker
      dockerfile: Dockerfile

  flora-ui:
    build:
      context: ./flora-ui
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_FLORA_CORE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - flora-core
